function throwError() {
  throw('这是一个错误');
}

export default throwError;